PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
BASE		 <http://example.org/kulturarena/>
#Which musical performers' consecutive concerts were most years apart and by how many years?
SELECT ?musician ?yearsApart
WHERE {
  ?concert1 rdf:type <Concert>;
            <performedBy> ?musician;
            <inYear> ?year1.
  
  ?concert2 rdf:type <Concert>;
            <performedBy> ?musician;
            <inYear> ?year2.
  
  FILTER(?concert1 != ?concert2 && ?year1 > ?year2)
  FILTER NOT EXISTS{
    ?concert3 rdf:type <Concert>;
            <performedBy> ?musician;
            <inYear> ?year3.
    FILTER(?year1 > ?year3 && ?year3 > ?year2)
  }
  BIND((xsd:integer(?year1) - xsd:integer(?year2)) AS ?yearsApart) 
}GROUP BY ?musician ?yearsApart
ORDER BY DESC(?yearsApart)
LIMIT 1


