PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
BASE		 <http://example.org/kulturarena/>
#how many concerts with musicians from which countrys were performed in 2015
SELECT ?country ?name (count(DISTINCT ?concert) as ?count)
WHERE {
    ?concert a <Concert>;
         <inYear> "2015"^^xsd:integer;
         <performedBy> ?musician.
    ?musician <comesFrom> ?country.
    ?country <hasName> ?name.	
}
GROUP BY ?country ?name 