PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX kul: <http://example.org/kulturarena/>
SELECT (COUNT(DISTINCT ?concert) AS ?count) 
WHERE { 
    ?concert a kul:Concert;
         kul:performedBy ?musician.
    ?musician kul:hasName "BOY".
}