PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
BASE		 <http://example.org/kulturarena/>
#how often did BOY perform?
#count
SELECT (COUNT(DISTINCT ?concert) AS ?count) 
WHERE { 
    ?concert a <Concert>;
         <performedBy> ?musician.
    ?musician <hasName> "BOY"@de.
}