
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX kul: <http://example.org/kulturarena/>
#with which musician did the most concerts take place?
#country-IRI, country name
SELECT ?country ?name 
WHERE {
  {
    ?concert a kul:Concert;
        kul:performedBy ?musician .
    ?musician kul:comesFrom ?country .
    ?country kul:hasName ?name.
  }
}GROUP BY ?country ?name
ORDER BY DESC(Count(?concert))
LIMIT 1

# PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
# PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
# PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
# PREFIX kul: <http://example.org/kulturarena/>
# SELECT ?country ?name 
# WHERE {
#   {
#     ?concert a kul:Concert;
#         kul:performedBy ?musician .
#     ?musician kul:comesFrom ?country .
#     ?country kul:hasName ?name.
#   }
#   {
#     Select ?country ?name  (COUNT(?concert) AS ?concertCount)
#     WHERE{
#           ?concert kul:performedBy ?musician .
#           ?musician kul:comesFrom ?country .
#           ?country kul:hasName ?name.
#    	}GROUP BY ?country ?name
#   }
# }
# GROUP BY ?country ?name
# ORDER BY DESC(?concertCount)
# LIMIT 1