PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
BASE		 <http://example.org/kulturarena/>
#from which country do the most musician come from who performed a concert?
#country-IRI, country name
SELECT ?country ?name 
WHERE {
  {
    ?concert a <Concert>;
        <performedBy> ?musician .
    ?musician <comesFrom> ?country .
    ?country <hasName> ?name.
  }
}GROUP BY ?country ?name
ORDER BY DESC(Count(?concert))
LIMIT 1

