PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX kul: <http://example.org/kulturarena/>
#which genre is assigned to the musician "Yasmine HAmdan" and what MusicBrainzID does she have?
# musician-IRI, genre name, MusicBrainz artist ID
SELECT ?musician ?musicBrainzId ?genre
WHERE { 
  ?musician kul:hasName "Yasmine Hamdan";
            kul:hasGenre ?genre;
            kul:hasMusicBrainzId ?musicBrainzId.
}